CREATE TABLE [dbo].[APTOL_Log]
(
    LogId Int IDENTITY(1,1) NOT NULL, 
    LogDateTime DateTime NOT NULL CONSTRAINT APTOL_Log_LogDateTime DEFAULT '3000-01-01', 
    ResepId VARCHAR(20) NOT NULL CONSTRAINT APTOL_Log_ResepId DEFAULT '',
    Request VARCHAR(1024) NOT NULL CONSTRAINT APTOL_Log_Request DEFAULT '',
    Response VARCHAR(1024) NOT NULL CONSTRAINT APTOL_Log_Response DEFAULT '',
    [Message] VARCHAR(1024) NOT NULL CONSTRAINT APTOL_Log_Message DEFAULT ''

    CONSTRAINT PK_APTOL_Log_LogId PRIMARY KEY CLUSTERED(LogId)
)