-- INSERT INTO JKNMW_AssesmentPelayanan (AssesmentPelayananId, AssesmentPelayananName) VALUES
--     ('1', 'Poli spesialis tidak tersedia pada hari sebelumnya'),
--     ('2', 'Jam Poli telah berakhir pada hari sebelumnya'),
--     ('3', 'Dokter Spesialis yang dimaksud tidak praktek pada hari sebelumnya'),
--     ('4', 'Atas Instruksi RS'),
--     ('5', 'Tujuan Kontrol');
-- 
--  