CREATE TABLE vclaim_sep (
    fs_no_sep VARCHAR(19) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_sep DEFAULT (''),
    fd_tgl_trs VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_trs DEFAULT ('3000-01-01'),
    fs_jam_trs VARCHAR(8) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_jam_trs DEFAULT (''),

    fs_kd_reg VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_reg DEFAULT (''),
    fs_no_mr VARCHAR(15) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_mr DEFAULT (''),
    fs_no_peserta VARCHAR(13) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_peserta DEFAULT (''),
    fs_nm_peserta VARCHAR(50) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_peserta DEFAULT (''),
    fs_jns_peserta VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_jns_peserta DEFAULT (''),
    fs_no_telp VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_telp DEFAULT (''),

    fs_kd_tipe_jaminan VARCHAR(5) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_tipe_jaminan DEFAULT (''),
    fs_kd_kelas_peserta VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_kelas_peserta DEFAULT (''),
    fs_nm_kelas_peserta VARCHAR(15) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_kelas_peserta DEFAULT (''),
    fb_cob BIT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fb_cob DEFAULT (0),
    fs_nm_cob VARCHAR(40) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_cob DEFAULT (''),
    fs_no_cob VARCHAR(20) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_cob DEFAULT (''),

    fs_no_rujukan VARCHAR(19) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_rujukan DEFAULT (''),
    fd_tgl_rujukan VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_rujukan DEFAULT ('3000-01-01'),
    fs_jam_rujukan VARCHAR(8) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_jam_rujukan DEFAULT (''),
    fs_kd_tipe_faskes VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_tipe_faskes DEFAULT (''),
    fs_kd_ppk_rujukan VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_ppk_rujukan DEFAULT (''),
    fs_nm_ppk_rujukan VARCHAR(50) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_ppk_rujukan DEFAULT (''),
    fs_provider VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_provider DEFAULT (''),

    fs_kd_diagnosa VARCHAR(6) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_diagnosa DEFAULT (''),
    fs_nm_diagnosa VARCHAR(1024) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_diagnosa DEFAULT (''),

    fs_kd_jns_pelayanan VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_jns_pelayanan DEFAULT (''),
    fs_kd_layanan VARCHAR(5) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_layanan DEFAULT (''),
    fb_poli_eksekutif BIT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fb_poli_eksekutif DEFAULT (0),
    fb_katarak BIT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fb_katarak DEFAULT (0),
    fs_kd_dpjp_layanan VARCHAR(6) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_dpjp_layanan DEFAULT (''),
    fs_kd_kelas_rawat VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_kelas_rawat DEFAULT (''),
    fs_catatan TEXT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_catatan DEFAULT (''),
    fs_kd_laka VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_laka DEFAULT (''),
    fd_tgl_laka VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_laka DEFAULT ('3000-01-01'),
    fs_kd_prop_laka VARCHAR(2) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_prop_laka DEFAULT (''),
    fs_nm_prop_laka VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_prop_laka DEFAULT (''),
    fs_kd_kab_laka VARCHAR(4) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_kab_laka DEFAULT (''),
    fs_nm_kab_laka VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_kab_laka DEFAULT (''),
    fs_kd_kec_laka VARCHAR(4) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_kec_laka DEFAULT (''),
    fs_nm_kec_laka VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_kec_laka DEFAULT (''),
    fs_keterangan_laka VARCHAR(50) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_keterangan_laka DEFAULT (''),
    fs_kd_penjamin_laka VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_penjamin_laka DEFAULT (''),
    fb_suplesi BIT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fb_suplesi DEFAULT (0),
    fs_no_sep_suplesi VARCHAR(19) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_sep_suplesi DEFAULT (''),
    fs_no_skdp VARCHAR(25) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_skdp DEFAULT (''),
    fs_kd_dpjp VARCHAR(6) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_dpjp DEFAULT (''),
    fs_nm_dpjp VARCHAR(60) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_nm_dpjp DEFAULT (''),
    fb_prb BIT NOT NULL CONSTRAINT DF_VCLAIM_Sep_fb_prb DEFAULT (0),
    fs_prb VARCHAR(50) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_prb DEFAULT (''),
    fs_sub_spesialis VARCHAR(40) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_sub_spesialis DEFAULT (''),
    fs_kd_tujuan_kunjungan VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_tujuan_kunjungan DEFAULT (''),
    fs_kd_flag_procedure VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_flag_procedure DEFAULT (''),
    fs_kd_penunjang VARCHAR(2) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_penunjang DEFAULT (''),
    fs_kd_assesment_pel VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_assesment_pel DEFAULT (''),
    fs_kd_pembiayaan VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_pembiayaan DEFAULT (''),
    fs_penanggung_jawab VARCHAR(50) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_penanggung_jawab DEFAULT (''),
    fd_tgl_pulang VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_pulang DEFAULT ('3000-01-01'),
    fs_kd_status_pulang VARCHAR(1) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_status_pulang DEFAULT (''),
    fd_tgl_meninggal VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_meninggal DEFAULT ('3000-01-01'),
    fs_no_surat_kematian VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_surat_kematian DEFAULT (''),
    fs_no_lp_manual VARCHAR(30) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_lp_manual DEFAULT (''),
    fd_tgl_jam_trs VARCHAR(19) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_jam_trs DEFAULT ('3000-01-01'),
    fs_kd_petugas VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_petugas DEFAULT (''),
    fd_tgl_void VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fd_tgl_void DEFAULT ('3000-01-01'),
    fs_jam_void VARCHAR(8) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_jam_void DEFAULT (''),
    fs_kd_petugas_void VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_petugas_void DEFAULT (''),

    crt_tgl VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_crt_tgl DEFAULT ('3000-01-01'),
    crt_jam VARCHAR(8) NOT NULL CONSTRAINT DF_VCLAIM_Sep_crt_jam DEFAULT (''),
    crt_ipa VARCHAR(40) NOT NULL CONSTRAINT DF_VCLAIM_Sep_crt_ipa DEFAULT (''),
    crt_ver VARCHAR(12) NOT NULL CONSTRAINT DF_VCLAIM_Sep_crt_ver DEFAULT (''),
    crt_usr VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_crt_usr DEFAULT (''),
    upd_tgl VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_upd_tgl DEFAULT ('3000-01-01'),
    upd_jam VARCHAR(8) NOT NULL CONSTRAINT DF_VCLAIM_Sep_upd_jam DEFAULT (''),
    upd_ipa VARCHAR(40) NOT NULL CONSTRAINT DF_VCLAIM_Sep_upd_ipa DEFAULT (''),
    upd_ver VARCHAR(12) NOT NULL CONSTRAINT DF_VCLAIM_Sep_upd_ver DEFAULT (''),
    upd_usr VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_upd_usr DEFAULT (''),

    fs_kd_trs VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_kd_trs DEFAULT (''),
    fs_jenis_kelamin VARCHAR(10) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_jenis_kelamin DEFAULT (''),
    fs_norujukinternal VARCHAR(19) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_norujukinternal DEFAULT (''),
    fs_no_lp_kll VARCHAR(100) NOT NULL CONSTRAINT DF_VCLAIM_Sep_fs_no_lp_kll DEFAULT ('')
);