CREATE TABLE [dbo].[APTOL_ResepMidware]
(
    --  KEY
    ResepMidwareId	VARCHAR(26) NOT NULL CONSTRAINT APTOL_ResepMidware_ResepMidwareId DEFAULT '',
    ResepMidwareDate DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_ResepMidwareDate DEFAULT '3000-01-01',

    -- EMR
    ChartId VARCHAR(14) NOT NULL CONSTRAINT APTOL_ResepMidware_ChartId DEFAULT '',
    ResepRsId VARCHAR(10) NOT NULL CONSTRAINT APTOL_ResepMidware_ResepRsId DEFAULT '',

    -- APTOL Related
    ReffId VARCHAR(30) NOT NULL CONSTRAINT APTOL_ResepMidware_ReffId DEFAULT '',
    JenisObatId VARCHAR(2) NOT NULL CONSTRAINT APTOL_ResepMidware_JenisObatId DEFAULT '',
    Iterasi INT NOT NULL CONSTRAINT APTOL_ResepMidware_Iterasi DEFAULT 0,

    -- SEP
    SepId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepMidware_SepId DEFAULT '',
    SepDate DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_SepDate DEFAULT '3000-01-01',
    SepNo VARCHAR(30) NOT NULL CONSTRAINT APTOL_ResepMidware_SepNo DEFAULT '',
    NoPeserta VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepMidware_NoPeserta DEFAULT '',
    RegId VARCHAR(10) NOT NULL CONSTRAINT APTOL_ResepMidware_RegId DEFAULT '',
    RegDate DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_RegDate DEFAULT '3000-01-01',
    PasienId VARCHAR(15) NOT NULL CONSTRAINT APTOL_ResepMidware_PasienId DEFAULT '',
    PasienName VARCHAR(60) NOT NULL CONSTRAINT APTOL_ResepMidware_PasienName DEFAULT '',
    DokterId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepMidware_DokterId DEFAULT '',
    DokterName VARCHAR(100) NOT NULL CONSTRAINT APTOL_ResepMidware_DokterNama DEFAULT '',

    -- PPK
    PpkId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepMidware_PpkId DEFAULT '',
    PpkName VARCHAR(100) NOT NULL CONSTRAINT APTOL_ResepMidware_PpkName DEFAULT '',
    
    -- POLI BPJS
    PoliBpjsId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepMidware_PoliBpjsId DEFAULT '',
    PoliBpjsName VARCHAR(100) NOT NULL CONSTRAINT APTOL_ResepMidware_PoliBpjsName DEFAULT '',

    -- BRIDGING STATE
    BridgeState VARCHAR(10) NOT NULL CONSTRAINT APTOL_ResepMidware_ResepMidwareState DEFAULT '', -- CREATED, SYNCED, UPLOADED
    CreateTimestamp DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_CreateTimestamp DEFAULT '3000-01-01',
    SyncTimestamp DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_SyncTimestamp DEFAULT '3000-01-01',
    UploadTimestamp DATETIME NOT NULL CONSTRAINT APTOL_ResepMidware_UploadTimestamp DEFAULT '3000-01-01',

    CONSTRAINT PK_APTOL_ResepMidware_ResepMidwareId PRIMARY KEY CLUSTERED(ResepMidwareId)
)
