CREATE TABLE JKNMW_EKlaim(
    EKlaimId VARCHAR(26) NOT NULL CONSTRAINT JKN_EKlaim_EKlaimId DEFAULT(''),
    EKlaimDate DATETIME NOT NULL CONSTRAINT JKN_EKlaim_EKlaimDate DEFAULT('3000-01-01'),
    
    SepNo VARCHAR(16) NOT NULL CONSTRAINT JKN_EKlaim_NomorSep DEFAULT(''),
    KartuBpjsNo VARCHAR(13) NOT NULL CONSTRAINT JKN_EKlaim_NomorKartu DEFAULT(''),
    
    PasienId VARCHAR(26) NOT NULL CONSTRAINT JKN_EKlaim_PasienId DEFAULT(''),
    PasienName VARCHAR(50) NOT NULL CONSTRAINT JKN_EKlaim_PasienName DEFAULT(''),
    BirthDate DATETIME NOT NULL CONSTRAINT JKN_EKlaim_TanggalLahir DEFAULT('3000-01-01'),
    Gender VARCHAR(1) NOT NULL CONSTRAINT JKN_EKlaim_Gender DEFAULT(''),
)