CREATE TABLE JKNMW_EKlaim(
    EKlaimId VARCHAR(26) NOT NULL CONSTRAINT JKNMW_EKlaim_EKlaimId DEFAULT(''),
    EKlaimDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_EKlaimDate DEFAULT('3000-01-01'),
    
    SepNo VARCHAR(16) NOT NULL CONSTRAINT JKNMW_EKlaim_NomorSep DEFAULT(''),
    KartuBpjsNo VARCHAR(13) NOT NULL CONSTRAINT JKNMW_EKlaim_NomorKartu DEFAULT(''),
    
    RegId VARCHAR(10) NOT NULL CONSTRAINT JKNMW_EKlaim_RegId DEFAULT(''),
    RegDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_TanggalReg DEFAULT('3000-01-01'),
    
    PasienId VARCHAR(26) NOT NULL CONSTRAINT JKNMW_EKlaim_PasienId DEFAULT(''),
    PasienName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_PasienName DEFAULT(''),
    BirthDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_TanggalLahir DEFAULT('3000-01-01'),
    Gender VARCHAR(1) NOT NULL CONSTRAINT JKNMW_EKlaim_Gender DEFAULT(''),
    
    CONSTRAINT PK_JKN_EKlaim PRIMARY KEY CLUSTERED (EKlaimId)
)
GO

CREATE UNIQUE INDEX UIX_JKNMW_EKlaim_SepNo 
    ON JKNMW_EKlaim(SepNo, EKlaimId)
    WITH(FILLFACTOR = 95)
GO

CREATE UNIQUE INDEX UI_JKNMW_EKlaim_RegId 
    ON JKNMW_EKlaim(RegId, EKlaimId)
    WITH(FILLFACTOR = 95)
GO