CREATE TABLE JKNMW_Payor(
    PayorId VARCHAR(3) NOT NULL CONSTRAINT DF_JKNMW_Payor_PayorId DEFAULT(''),
    PayorName VARCHAR(30) NOT NULL CONSTRAINT DF_JKNMW_Payor_PayorName DEFAULT(''),
    Code VARCHAR(5) NOT NULL CONSTRAINT DF_JKNMW_Payor_Code DEFAULT(''),
    
    CONSTRAINT PK_JKNMW_Payor PRIMARY KEY CLUSTERED (PayorId)
)

