CREATE TABLE JKNMW_Covid19Status(
  Covid19StatusId VARCHAR(1) NOT NULL CONSTRAINT DF_JKNMW_Covid19Status_Covid19StatusId DEFAULT(''),
  Covid19StatusName VARCHAR(30) NOT NULL CONSTRAINT DF_JKNMW_Covid19Status_Covid19StatusName DEFAULT(''),

  CONSTRAINT PK_JKNMW_Covid19Status PRIMARY KEY CLUSTERED (Covid19StatusId)
)

