-- INSERT INTO JKNMW_Covid19Status (Covid19StatusId, Covid19StatusName) VALUES
-- ('1', 'ODP - Orang Dalam Pemantauan'),
-- ('2', 'PDP - Pasien Dalam Perawatan'),
-- ('3', 'Terkonfirmasi Positif'),
-- ('4', 'Suspek'),
-- ('5', 'Probabel');
