CREATE TABLE JKNMW_GrouperIdrg(
    EKlaimId VARCHAR(26) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_EKlaimId DEFAULT (''),
    GrouperIdrgDate DATETIME NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_GrouperIdrgDate DEFAULT ('3000-01-01'),
    SepNo VARCHAR(26) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_SepNo DEFAULT (''),
    
    InfoResult VARCHAR(128) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_ResultInfo DEFAULT (''),
    JenisRawat VARCHAR(30) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_JenisRawat DEFAULT (''),
    MdcId VARCHAR(10) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_MdcId DEFAULT (''),
    MdcName VARCHAR(128) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_MdcName DEFAULT (''),
    DrgId VARCHAR(10) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_DrgId DEFAULT (''),
    DrgName VARCHAR(128) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_DrgName DEFAULT (''),
    StatusResult VARCHAR(30) NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_StatusResult DEFAULT (''),
    
    Phase INT NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_Phase DEFAULT (0),
    FinalTimeStamp DATETIME NOT NULL CONSTRAINT DF_JKNMW_GrouperIdrg_FinalTimeStamp DEFAULT ('3000-01-01'),
    
    CONSTRAINT PK_JKNMW_GrouperIdrg PRIMARY KEY CLUSTERED (EKlaimId)
)
GO

CREATE UNIQUE INDEX UIX_JKNMW_GrouperIdrg_SepNo ON JKNMW_GrouperIdrg (SepNo)
GO