CREATE TABLE JKNMW_EKlaim(
    EKlaimId VARCHAR(26) NOT NULL CONSTRAINT JKNMW_EKlaim_EKlaimId DEFAULT(''),
    EKlaimDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_EKlaimDate DEFAULT('3000-01-01'),
    
    SepNo VARCHAR(16) NOT NULL CONSTRAINT JKNMW_EKlaim_NomorSep DEFAULT(''),
    KartuBpjsNo VARCHAR(13) NOT NULL CONSTRAINT JKNMW_EKlaim_KartuBpjsNo DEFAULT(''),
    
    RegId VARCHAR(10) NOT NULL CONSTRAINT JKNMW_EKlaim_RegId DEFAULT(''),
    RegDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_TanggalReg DEFAULT('3000-01-01'),
    
    PasienId VARCHAR(26) NOT NULL CONSTRAINT JKNMW_EKlaim_PasienId DEFAULT(''),
    PasienName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_PasienName DEFAULT(''),
    BirthDate DATETIME NOT NULL CONSTRAINT JKNMW_EKlaim_TanggalLahir DEFAULT('3000-01-01'),
    Gender VARCHAR(1) NOT NULL CONSTRAINT JKNMW_EKlaim_Gender DEFAULT(''),
    
    DpjpId VARCHAR(6) NOT NULL CONSTRAINT JKNMW_EKlaim_DpjpId DEFAULT(''),
    DpjpName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_DpjpName DEFAULT(''),
    
    CaraMasukId VARCHAR(10) NOT NULL CONSTRAINT JKNMW_EKlaim_CaraMasukId DEFAULT(''),
    CaraMasukName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_CaraMasukName DEFAULT(''),
    
    KelasJknId VARCHAR(1) NOT NULL CONSTRAINT JKNMW_EKlaim_KelasJknId DEFAULT(''),
    KelasJknName VARCHAR(10) NOT NULL CONSTRAINT JKNMW_EKlaim_KelasJknName DEFAULT(''),
    KelasJknValue INT NOT NULL CONSTRAINT JKNMW_EKlaim_KelasJknValue DEFAULT(0),
    KelasTarifRsId VARCHAR(2) NOT NULL CONSTRAINT JKNMW_EKlaim_KelasTarifRsId DEFAULT(''),
    TarifPoliEksekutif DECIMAL(18,2) NOT NULL CONSTRAINT JKNMW_EKlaim_TarifPoliEksekutif DEFAULT(0),
    UpgradeIndikator INT NOT NULL CONSTRAINT JKNMW_EKlaim_UpgradeIndikator DEFAULT(0),
    AddPaymentProcentage DECIMAL(18,2) NOT NULL CONSTRAINT JKNMW_EKlaim_AddPaymentPersentase DEFAULT(0),
    
    DischargeStatusId VARCHAR(1) NOT NULL CONSTRAINT JKNMW_EKlaim_DischargeStatusId DEFAULT(''),
    DischargeStatusName VARCHAR(20) NOT NULL CONSTRAINT JKNMW_EKlaim_DischargeStatusName DEFAULT(''),
    
    PayorId VARCHAR(3) NOT NULL CONSTRAINT JKNMW_EKlaim_PayorId DEFAULT(''),
    PayorName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_PayorName DEFAULT(''),
     
    CoderPegId VARCHAR(6) NOT NULL CONSTRAINT JKNMW_EKlaim_CoderPegId DEFAULT(''),
    CoderPegName VARCHAR(50) NOT NULL CONSTRAINT JKNMW_EKlaim_CoderPegName DEFAULT(''),
    CoderNik VARCHAR(16) NOT NULL CONSTRAINT JKNMW_EKlaim_CoderNik DEFAULT(''),
    
    Los INT NOT NULL CONSTRAINT JKNMW_EKlaim_Los DEFAULT(0),

    CONSTRAINT PK_JKN_EKlaim PRIMARY KEY CLUSTERED (EKlaimId)
)
GO

CREATE UNIQUE INDEX UIX_JKNMW_EKlaim_SepNo 
    ON JKNMW_EKlaim(SepNo, EKlaimId)
    WITH(FILLFACTOR = 95)
GO

CREATE UNIQUE INDEX IX_JKNMW_EKlaim_RegId 
    ON JKNMW_EKlaim(RegId, EKlaimId)
    WITH(FILLFACTOR = 95)
GO