CREATE TABLE JKNMW_EKlaimReffBiaya(
    EKlaimId VARCHAR(26) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_EKlaimId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_NoUrut DEFAULT(0),
    TrsId VARCHAR(20) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_TrsId DEFAULT(''),
    ReffBiayaId VARCHAR(20) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_ReffBiayaId DEFAULT(''),
    ReffClass INT NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_ReffClass DEFAULT(0),
    KetBiaya VARCHAR(60) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_KetBiaya DEFAULT(''),
    Nilai DECIMAL(18,2) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_Nilai DEFAULT(0),
    SkemaTarifJknId VARCHAR(2) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_SkemaTarifJknId DEFAULT(''),
    SkemaTarifJknName VARCHAR(20) NOT NULL CONSTRAINT JKNMW_EKlaimReffBiaya_SkemaTarifJknName DEFAULT(''),

    CONSTRAINT JKNMW_EKlaimReffBiaya_pk PRIMARY KEY CLUSTERED (EKlaimId, NoUrut)
)