-- INSERT INTO JKNMW_DischargeStatus (DischargeStatusId, DischargeStatusName) VALUES
-- ('1', 'Atas Persetujuan Dokter'),
-- ('2', 'Dirujuk'),
-- ('3', 'Atas Permintaan Sendiri'),
-- ('4', 'Meninggal'),
-- ('5', 'Lain-lain');
