CREATE TABLE JKNMW_Peg(
    PegId VARCHAR(26) NOT NULL CONSTRAINT DF_JKNMW_Peg_PegId DEFAULT(''),
    PegName VARCHAR(30) NOT NULL CONSTRAINT DF_JKNMW_Peg_PegName DEFAULT(''),
    Nik VARCHAR(16) NOT NULL CONSTRAINT DF_JKNMW_Peg_Code DEFAULT(''),

    CONSTRAINT PK_JKNMW_Peg PRIMARY KEY CLUSTERED (PegId)
)

