CREATE TABLE [dbo].[APTOL_ResepItem]
(
    ResepId	VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepItem_ResepId DEFAULT '',  
    OrderNo INT NOT NULL CONSTRAINT APTOL_ResepItem_OrderNo DEFAULT 0, 
    IsRacik BIT NOT NULL CONSTRAINT APTOL_ResepItem_IsRacik DEFAULT 0,
    RacikId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepItem_RacikId DEFAULT '',
    BarangId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepItem_BarangId DEFAULT '',
    DphoId VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepItem_DphoId DEFAULT '',
    DphoName VARCHAR(50) NOT NULL CONSTRAINT APTOL_ResepItem_DphoName DEFAULT '',
    Signa1 INT NOT NULL CONSTRAINT APTOL_ResepItem_Signa1 DEFAULT 0, 
    Signa2 INT NOT NULL CONSTRAINT APTOL_ResepItem_Signa2 DEFAULT 0, 
    Jho INT NOT NULL CONSTRAINT APTOL_ResepItem_Jho DEFAULT 0,
    Qty INT NOT NULL CONSTRAINT APTOL_ResepItem_Qty DEFAULT 0,
    Note VARCHAR(20) NOT NULL CONSTRAINT APTOL_ResepItem_Note DEFAULT ''

    CONSTRAINT PK_APTOL_ResepItem_ResepId_BarangId PRIMARY KEY (ResepId, BarangId)
)
