CREATE TABLE [dbo].[APTOL_Resep]
(
    ResepId	VARCHAR(20) NOT NULL CONSTRAINT APTOL_Resep_PenjualanId DEFAULT '',  
    ReffId VARCHAR(30) NOT NULL CONSTRAINT APTOL_Resep_ReffId DEFAULT '', 
    SepId VARCHAR(20) NOT NULL CONSTRAINT APTOL_Resep_SepId DEFAULT '',
    ResepDate DateTime NOT NULL CONSTRAINT APTOL_Resep_ResepDate DEFAULT '3000-01-01',
    NoPeserta VARCHAR(20) NOT NULL CONSTRAINT APTOL_Resep_NoPeserta DEFAULT '',
    JenisObatId VARCHAR(2) NOT NULL CONSTRAINT APTOL_Resep_JenisObatId DEFAULT '',
    EntryDate DateTime NOT NULL CONSTRAINT APTOL_Resep_EntryDate DEFAULT '3000-01-01',
    FaskesAsal VARCHAR(20) NOT NULL CONSTRAINT APTOL_Resep_FaskesAsal DEFAULT ''

    CONSTRAINT PK_APTOL_Resep_ResepId PRIMARY KEY CLUSTERED(ResepId)
)
